import { cookies } from 'next/headers'
import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BookOpen, ExternalLink, HeartHandshake, KeyRound, Link2, Users } from 'lucide-react'
import { query } from '@/lib/db'
import { validateSession } from '@/lib/auth'
import { SiteHeader } from '@/components/SiteHeader'
import { AccountControls } from '@/components/AccountControls'

async function stats(){const [users,subs,content,teachers,recentContent,recentLinks]=await Promise.all([query<any>('SELECT COUNT(*) as count FROM yar_users'),query<any>('SELECT COUNT(*) as count FROM yar_subscriptions WHERE end_date > NOW()'),query<any>('SELECT COUNT(*) as count FROM yar_content_items WHERE published=true'),query<any>('SELECT COUNT(*) as count FROM yar_teachers'),query<any>('SELECT id,title,content_type,created_at,view_count FROM yar_content_items ORDER BY created_at DESC LIMIT 5'),query<any>('SELECT id,code,expires_at,max_redemptions,current_redemptions FROM yar_subscription_links ORDER BY created_at DESC LIMIT 5')]);return{users:users[0]?.count||0,subs:subs[0]?.count||0,content:content[0]?.count||0,teachers:teachers[0]?.count||0,recentContent,recentLinks}}

export default async function AdminPage(){const token=(await cookies()).get('session_token')?.value;const user=token?await validateSession(token):null;if(!user||user.role!=='admin')redirect('/');const s=await stats();return <div className="page"><SiteHeader userName={user.name} isAdmin/><main className="shell section"><span className="section-kicker"><KeyRound/> اتاق فرمان</span><h1 className="display" style={{fontSize:'clamp(2.3rem,5vw,3.8rem)'}}>پنل مدیریت</h1><p className="lead" style={{marginTop:'.5rem'}}>همه‌چیز زیر دست توست؛ سریع، واضح و بدون شلوغی.</p>
<div className="stat-grid" style={{marginTop:'2rem'}}><div className="card stat-card"><div><p className="muted">کاربران</p><p className="stat-num">{s.users}</p></div><Users/></div><div className="card stat-card" style={{background:'var(--sunflower)'}}><div><p>اشتراک فعال</p><p className="stat-num">{s.subs}</p></div><KeyRound/></div><div className="card stat-card" style={{background:'var(--teal)',color:'var(--paper)'}}><div><p>محتوا</p><p className="stat-num">{s.content}</p></div><BookOpen/></div><div className="card stat-card" style={{background:'var(--berry)',color:'var(--paper)'}}><div><p>معلم‌ها</p><p className="stat-num">{s.teachers}</p></div><HeartHandshake/></div></div>
<section className="section" style={{paddingBottom:'2rem'}}><h2 className="section-title" style={{fontSize:'1.8rem',marginBottom:'1rem'}}>کارهای سریع</h2><div className="admin-actions"><Link href="/admin/teachers" className="card card-hover action-card"><HeartHandshake/><h3 style={{fontWeight:800,fontSize:'1.2rem'}}>مدیریت معلم‌ها</h3><p className="muted">افزودن، ویرایش و ترتیب نمایش</p></Link><Link href="/admin/subscriptions/new" className="card card-hover action-card"><Link2/><h3 style={{fontWeight:800,fontSize:'1.2rem'}}>ساخت کد اشتراک</h3><p className="muted">کد تازه برای کاربران بساز</p></Link><Link href="/" className="card card-hover action-card"><ExternalLink/><h3 style={{fontWeight:800,fontSize:'1.2rem'}}>مشاهده سایت</h3><p className="muted">نتیجه تغییرات را ببین</p></Link></div></section>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:'1.5rem'}}><section className="card account-panel"><h2 style={{fontSize:'1.4rem',fontWeight:800,marginBottom:'1rem'}}>محتوای اخیر</h2>{s.recentContent.length?s.recentContent.map((x:any)=><div className="data-row" key={x.id}><div><b>{x.title}</b><p className="muted" style={{fontSize:'.85rem'}}>{x.content_type}</p></div><span>{x.view_count||0} بازدید</span></div>):<p className="muted">محتوایی نیست.</p>}</section><section className="card account-panel"><h2 style={{fontSize:'1.4rem',fontWeight:800,marginBottom:'1rem'}}>کدهای اخیر</h2>{s.recentLinks.length?s.recentLinks.map((x:any)=><div className="data-row" key={x.id}><b className="ltr">{x.code}</b><span>{x.current_redemptions}/{x.max_redemptions}</span></div>):<p className="muted">کدی نیست.</p>}</section></div>
<div className="card" style={{marginTop:'1.5rem'}}><AccountControls/></div></main></div>}
