import { cookies } from 'next/headers'
import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BookOpen, CheckCircle2, Clapperboard, Crown, History, Play, Sparkles } from 'lucide-react'
import { query } from '@/lib/db'
import { hasActiveSubscription } from '@/lib/subscriptions'
import { validateSession } from '@/lib/auth'
import { SiteHeader, SiteFooter } from '@/components/SiteHeader'
import { AccountControls } from '@/components/AccountControls'

async function getData(userId:string){const hasSubscription=await hasActiveSubscription(userId);const history=await query<any>(`SELECT vh.*, c.title, c.thumbnail_url, c.duration_seconds, c.content_type FROM yar_viewing_history vh JOIN yar_content_items c ON vh.content_id=c.id WHERE vh.user_id=$1 ORDER BY vh.last_watched_at DESC LIMIT 6`,[userId]);const continuing=history.filter(x=>!x.completed&&x.progress_seconds>0).slice(0,4);return{hasSubscription,history,continuing}}

export default async function DashboardPage(){const token=(await cookies()).get('session_token')?.value;const user=token?await validateSession(token):null;if(!user)redirect('/login');const{hasSubscription,history,continuing}=await getData(user.id);return <div className="page"><SiteHeader userName={user.name} isAdmin={user.role==='admin'}/><main className="shell section"><span className="section-kicker"><Sparkles/> فضای خودت</span><h1 className="display" style={{fontSize:'clamp(2.2rem,5vw,3.8rem)'}}>سلام {user.name}!</h1><p className="lead" style={{marginTop:'.6rem'}}>امروز دوست داری چی یاد بگیری؟</p>
<section className="card" style={{marginTop:'2rem',padding:'1.7rem',background:hasSubscription?'var(--teal)':'var(--sunflower)',color:hasSubscription?'var(--paper)':'var(--ink)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'1rem',flexWrap:'wrap'}}><div style={{display:'flex',alignItems:'center',gap:'1rem'}}>{hasSubscription?<CheckCircle2 style={{width:38,height:38}}/>:<Crown style={{width:38,height:38}}/>}<div><h2 style={{fontSize:'1.35rem',fontWeight:800}}>{hasSubscription?'اشتراک تو فعال است':'دنیای کامل را باز کن'}</h2><p>{hasSubscription?'به همه محتوا دسترسی داری.':'با اشتراک به همه درس‌ها و فیلم‌ها دسترسی پیدا کن.'}</p></div></div>{!hasSubscription&&<Link href="/subscription" className="button button-primary">دیدن اشتراک</Link>}</div></section>
<section className="section" style={{paddingBottom:'2rem'}}><h2 className="section-title" style={{fontSize:'1.8rem',marginBottom:'1rem'}}>میان‌بُرهای تو</h2><div className="tiles"><Link href="/curriculum" className="card card-hover tile"><div className="tile-ico" style={{background:'var(--sunflower)'}}><BookOpen/></div><h3 style={{fontSize:'1.3rem',fontWeight:800}}>کلاس درس</h3><p className="muted">ریاضی، فارسی، علوم و بیشتر</p></Link><Link href="/entertainment" className="card card-hover tile"><div className="tile-ico" style={{background:'var(--berry)',color:'var(--paper)'}}><Clapperboard/></div><h3 style={{fontSize:'1.3rem',fontWeight:800}}>وقت تفریح</h3><p className="muted">فیلم‌ها و انیمیشن‌های کودکانه</p></Link></div></section>
{continuing.length>0&&<section style={{marginBottom:'3rem'}}><span className="section-kicker"><Play/> ادامه تماشا</span><div className="content-grid">{continuing.map(x=><Link href={`/watch/${x.content_id}`} key={x.id} className="card card-hover"><div style={{aspectRatio:'16/9',background:'var(--ink)'}}>{x.thumbnail_url&&<img src={x.thumbnail_url || "/placeholder.svg"} alt={x.title} style={{width:'100%',height:'100%',objectFit:'cover'}}/>}</div><div style={{padding:'1rem'}}><b>{x.title}</b></div></Link>)}</div></section>}
{history.length>0&&<section style={{marginBottom:'3rem'}}><span className="section-kicker"><History/> دیده‌های اخیر</span><div className="content-grid">{history.map(x=><Link href={`/watch/${x.content_id}`} key={x.id} className="card" style={{padding:'1rem'}}><b>{x.title}</b></Link>)}</div></section>}
<div className="card"><AccountControls/></div></main><SiteFooter/></div>}
